### ISSUE TITLE
add --only-mining --only-incomig --only-outstanding

### ISSUE THREAD

**Issue by snipeTR** [51FuR4nk/wallet-monitor#5]
![image](https://user-images.githubusercontent.com/31975916/162343697-bb465a3b-0aeb-44b9-8aec-e17e7e2eb49b.png)
The system shows the transfer I sent and even the returned change balance as income. it has to be separated.

![image](https://user-images.githubusercontent.com/31975916/162344163-4c5df685-d13e-4966-b449-33726593d573.png)
In the hour part, the shipping is also ridiculous.

**Comment by 51FuR4nk** [comment]
I will need to investigate this...
because I filter the transaction using the parameter Coinbase = True if I got it correct from dero documentation only the the miner rewards should have coibase True.

could you please paste the output of the following commands:
`curl -X POST   http://127.0.0.1:10103/json_rpc   -H 'content-type: application/json'   -d '{"jsonrpc": "2.0","id": "1","method": "GetTransfers","params": {"coinbase": true, "min_height":186812, "max_height": 186814}}'`
I just want to confirm that filtering by coinbase bring out those transactions

I had a couople of "normal" trasaction on my wallet but those are not displayed...
by normal I mean wallet to wallet

**Comment by snipeTR** [comment]
![image](https://user-images.githubusercontent.com/31975916/162472294-d2216714-0cfc-4de1-be7d-9ecdae0dc39c.png)
